version: '3'

services:
    db:
        build: ./mysql/
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        container_name: db_container
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        build: ./wordpress/
        restart: always
        ports:
            - "8000:80"
        container_name: wordpress_container
        environment:
            WORDPRESS_DB_HOST: db:3306  
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
